"""add ui_language to users

Revision ID: e0099bfe46a7
Revises: 70b21cb1d626
Create Date: 2026-10-07 13:26:30.648992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0099bfe46a7'
down_revision: Union[str, Sequence[str], None] = '70b21cb1d626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ui_language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ui_language')
    # ### end Alembic commands ###
